### ISSUE TITLE
wrong APK attached to 0.8.5 release

### ISSUE THREAD

**Issue by IzzySoft** [r57zone/EasyNotes#1]
Could you please replace the APK attached to release 0.8.5? It's the one from 0.8.4. Thanks!

**Comment by r57zone** [comment]
Hi, I haven't made any changes in the Android version yet, recent changes concern improvements to the PC version app (dark theme and settings).
The numbering of applications is not entirely correct, because it confuses users, but at the moment 0.8.4 is the latest version for Android.

**Comment by IzzySoft** [comment]
Ah, I see – thought it was an accident. To avoid further irritation, maybe remove the 0.8.4 APK from the 0.8.5 tag then? You've left a pointer in the description, and it's still available at the 0.8.4 tag.

Just wondering, don't feel pressed :wink:

**Comment by r57zone** [comment]
Github "hidden" (spoiler) files from old releases, users who are not familiar with github may face the fact that they simply will not see the APK file. I added a description and it will probably be clearer now.
Thanks for the feedback, you will need to think about how to make it more convenient.

**Comment by IzzySoft** [comment]
Yes, indeed, Github does that – but so does e.g. Gitea (look at codeberg.org if you don't know it), and I assume others (like Gogs at notabug.org, or GitLab) do the same. Maybe I'm too used to it that I find it obvious – it's not that hard to find IMHO; especially as you explicitly pointed it out in the current release's description (maybe `(v0.8.4 is the last – just open the assets blog below)` would remove all remaining doubts :wink:).

But as you wish, I won't nag you any further but accept your choice. As I wrote, I opened this issue because I suspected an accidentally misplaced file. That has been clarified now, thanks for your explanation! So if you feel the issue solved, it can be closed.

**Comment by r57zone** [comment]
I updated the Android version to 0.8.5 and added some improvements like automatic sync after startup. Before updating, be sure to sync your notes with your PC so they won't get lost when you reinstall the app.
https://github.com/r57zone/EasyNotes/releases

**Comment by IzzySoft** [comment]
Thanks! Looks like `versionCode` was not increased (APK still has `10` as with 0.8.4), though, so Android still counts it being the same version :wink:

```
package: name='com.r57zone.easynotes' versionCode='10' versionName='0.8.4' platformBuildVersionName='8.0.0'
package: name='com.r57zone.easynotes' versionCode='10' versionName='0.8.5' platformBuildVersionName='8.0.0'
```

**Comment by r57zone** [comment]
Fixed, thanks.

**Comment by IzzySoft** [comment]
Confirmed – thanks again!
