### ISSUE TITLE
Feature Request: Linkify URLs

### ISSUE THREAD

**Issue by Darthagnon** [r57zone/EasyNotes#2]
Would it be possible to implement an option to "Linkify URLs", opening addresses with their default handlers?
```
https://www.google.com --> default web browser
http://google.com --> default web browser
ftp://example --> ftp handler
mailto:name@example.org --> email client
magnet:3xample --> torrent client
C:\Windows\System32 --> Windows File Explorer or whatever default file explorer
```

I'm currently using [Cresstone Notes](https://cresstone.com/apps/notes/), but am wanting to replace it with a better notes application. It does have a couple more features: linkify URLs, Grep of notes contents, and text/title search.

**Comment by r57zone** [comment]
That is, if there is an email or a website in a note, then it was opened on click?

**Comment by Darthagnon** [comment]
Yes, something like that. Like how Notepad++ and Cresstone Notes do it, would be nice.

I just went a little bit crazy with my first comment, and listed a bunch of URI examples (I don't think any other notes program parses these, though).

**Comment by r57zone** [comment]
I'll think about how to add it.

**Comment by Darthagnon** [comment]
Thank you so much!

**Comment by r57zone** [comment]
I tried a couple of methods, but couldn't do it in an easy way due to using textarea. I'm afraid I won't be able to implement this. Sorry.

**Comment by Darthagnon** [comment]
Fair enough. Thank you for trying!
