### ISSUE TITLE
[Enhancement] Option to change database/config file location

### ISSUE THREAD

**Issue by IPeluchito** [r57zone/EasyNotes#4]
Could it be possible to include an option to change the location of the database and configuration file?...I would greatly appreciate it.
Also, I would like to translate the program into Spanish, how could I do it?

**Comment by IPeluchito** [comment]
Yes, I was referring to the PC version...Thanks! and well, I'll wait for you to add support for custom translations to be able to translate the program into Spanish...
Blessings!

**Comment by r57zone** [comment]
Hi @IPeluchito, could you translate it into Spanish? so that I can immediately include the translation of the new version.

Here is the file for the Windows version:
[English.txt](https://github.com/r57zone/EasyNotes/files/14322537/English.txt)
(when saving, use Notepad to make sure the encoding is Ansi).

Here are the lines for the Android/iOS/Web version:
```
IDS_MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
IDS_DAYOFWEEK = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
IDS_TODAY = 'Today';
IDS_YESTERDAY = 'Yesterday';
IDS_DAYSAGO = 'days ago';
IDS_NEW_NOTE = 'New note';
IDS_NOTES = 'Notes';

IDS_SETTINGS = 'Settings';
IDS_SYNC_ADDRESS = 'IP or domain';
IDS_SYNC_PORT = 'Port';
IDS_AUTOSEARCH_IP = 'Autosearch IP address';
IDS_ABOUT_SYNC = 'IP and port or domain to sync notes with your PC or web server.';
IDS_AUTO_SYNC = 'Sync at startup';
IDS_ABOUT_AUTO_SYNC = 'Automatically sync on app launch.';

IDS_FULL_RESET = 'Full reset';
IDS_CONFIRM_FULL_RESET = 'Do you really want to reset everything? All notes and settings will be deleted.';
IDS_DARK_THEME = 'Dark theme';
IDS_THEME_TIME_DEPENDENT = 'Theme is time dependent';
IDS_ABOUT_THEME_TIME = 'The dark theme turns on automatically from 06:00 pm to 08:00 am.';
IDS_LAST_UPDATE = 'Last update: ';
IDS_LOCAL_STORAGE = 'Local storage: %s of 5000 KB';

IDS_DATE_UPDATE = 'Date will be update';
IDS_DATE_NOT_UPDATE = 'Date will not be update';
IDS_AUTH_REJECT = 'Authorization rejected';
IDS_SYNC_SUCCESSFUL = 'Sync successful';
IDS_SYNC_ERROR = 'Sync error';
IDS_SYNC_NEED_CONNECT = 'Need connect to the network for sync';
IDS_CONNECTION_FAILED = 'Connection failed';
```
Thank you

**Comment by IPeluchito** [comment]
Hi @r57zone, here are the translations in ANSI format:
[Spanish.txt](https://github.com/r57zone/EasyNotes/files/14389918/Spanish.txt)
[Spanish AiW.txt](https://github.com/r57zone/EasyNotes/files/14389920/Spanish.AiW.txt)

**Comment by r57zone** [comment]
@IPeluchito Thank you, I will add the translation to the Windows version. Coming to Android in the next release. Could you also save the Android translation to UTF8 (UTF8 is supported there).

**Comment by r57zone** [comment]
I also updated the archive with the Windows version (EasyNotes.1.0.5.Portable.zip), could you check if everything is fine with Spanish 
https://github.com/r57zone/EasyNotes/releases/

**Comment by IPeluchito** [comment]
@r57zone, here are the translations in UTF-8 format:
[Spanish.txt](https://github.com/r57zone/EasyNotes/files/14394142/Spanish.txt)
[Spanish.AiW.txt](https://github.com/r57zone/EasyNotes/files/14394143/Spanish.AiW.txt)

The translation is perfect, the only drawback I noticed is this:
![snip_00007](https://github.com/r57zone/EasyNotes/assets/64821708/236cf60d-95a4-4f61-b818-a9e07e700697)
![snip_00008](https://github.com/r57zone/EasyNotes/assets/64821708/e9e8cc1a-2207-4f54-b89d-c94c04793ad4)

**Comment by r57zone** [comment]
Thanks, I'll fix it in next release

**Comment by r57zone** [comment]
Added Spanish support for Android app and fixed port issue in Windows version. Also added many other languages.
