### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [r57zone/EasyNotes#5]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by r57zone** [comment]
What are the security implications of this?

**Comment by IzzySoft** [comment]
See behind the link given. Quoting the relevant for you:

> * [Why debug certificate is not safe to sign android APKs?](https://stackoverflow.com/q/63497331/2533433)
> * [issues when using local debug keystore](https://proandroiddev.com/configuring-android-project-little-things-that-matter-d6a9d34c1ce0?gi=19305d0293a8#1daf)

From behind the first of the two links:

> […] the problem is that the debug certificate does not have a trust anchor, so the certificate can easily be replaced.

Further, a debug key doesn't indicate/show who signed the APK. It says it was signed by "Android Debug" – so anyone could have been this. While a production key includes at least a hint to your identity (with the details you provided when creating it). Here's the corresponding part from your current certificate:

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: cd3bdd2775b76166b67c0d0c7d01ee7efe5f8ac9ecb88286dd81eb8562510d35
Signer #1 certificate SHA-1 digest: 911a6ae311ef1b275c819f04b723ceeecc9e9c1e
Signer #1 certificate MD5 digest: 26526b638f60df32f847ae65d5dd1ca9
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

From a production cert of another app, for comparison:

```
Signer #1 certificate DN: CN=Saverio Morelli, L=Trento, C=IT
Signer #1 certificate SHA-256 digest: 0c9713a615e07bc9f401862158d3f5bdce056ca510010035e0fa84c812aeb203
Signer #1 certificate SHA-1 digest: 9179ee01ce9e1a1b6e96281f84b5327db2f27314
Signer #1 certificate MD5 digest: fed56b4fe7144c35aceaa3a29652508e
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

Which makes it much clearer where it comes from.

**Comment by IzzySoft** [comment]
So any plans for a properly signed APK, @r57zone?

**Comment by r57zone** [comment]
Sorry, but I don't think this will change security in any way. I also had problems launching apk signing it with its own certificate.

**Comment by IzzySoft** [comment]
This is the first time I hear about "problems launching apk signing it with its own certificate" – but well, my feet are not in your shoes :wink:

For some background: My repo, where your app is [currently listed](https://apt.izzysoft.de/packages/com.r57zone.easynotes), already does no longer accept new apps signed with debug keys. For apps already present (like yours) there's a grace period running now. If there's no solution (i.e. APKs signed using a release key) at the end of that period, those apps will be removed from the repo. That will be around March 2024 (no fixed date yet as I want to give developers sufficient time for the change).

**Comment by IzzySoft** [comment]
Looks like you switched to a different debug key now, and also `versionCode` was decreased. The previous release (from 9/2022) had `versionCode: 10004` and a certificate hash `cd3bdd2775b76166b67c0d0c7d01ee7efe5f8ac9ecb88286dd81eb8562510d35` – the one from today comes with `versionCode: 20` and a hash `69d41d78baf87c4662138b73d35f35cd8714f0e64d2e7d7ec98925f0eb40d259`. So nobody will receive an update – first because a lower `versionCode` means a downgrade, and second because the signature does not match.

As that APK would be re-downloaded by my updater on each update check, I had to temporarily disable update check for your app (the APKs wouldn't help anyone anyway). Crossing my fingers you can find a way to get this fixed.

**Comment by IzzySoft** [comment]
Just a last reminder, @r57zone: if this cannot be solved I'll have to remove your app [from my repo](https://apt.izzysoft.de/packages/com.r57zone.easynotes/) in a week. Makes no sense if updates are impossible as the key changes between releases, and APKs signed using debug keys won't be permitted in my repo anymore anyway.

**Comment by r57zone** [comment]
It's a pity, the version code was incorrect in the previous version, and the versions are also backwards incompatible (due to the death of websql). By signing with a generated certificate, my applications on Android 7.1 stopped installing; I did not try on a more recent one. I think it's better for the application to work on more versions.

**Comment by IzzySoft** [comment]
> By signing with a generated certificate, my applications on Android 7.1 stopped installing

With what error message? And was it a fresh/clean install, or was the app already installed on that device before? I doubt using a release key is the cause of install errors there. I'd rather expect something like an already installed version being in the way (naturally, you cannot simply update an already installed previous version if that was signed with a different key).

**Comment by IzzySoft** [comment]
Then I see that I can give you enough room for that. There are more "candidates" on the "cleanup list", so I can push yours to the end of the queue. Do you have any ETA?

**Comment by IzzySoft** [comment]
@r57zone ^^ any ETA? Hard cut coming for the debug keys.

**Comment by r57zone** [comment]
I updated the certificate and reuploaded the APK file. Thank you for reporting the problem.

**Comment by IzzySoft** [comment]
Thanks, that looks good! A little irritating though that `versionCode` was decreased from 10004 to 20 – but as folks need to uninstall and reinstall anyway, that should be OK (as long as future releases don't decrease it further :wink:)

Btw, scanner reports:

```
! repo/com.r57zone.easynotes_20.apk declares flag(s): usesCleartextTraffic
! repo/com.r57zone.easynotes_20.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

I guess `usesCleartextTraffic` is used inside LAN only (to sync with the counter-part on the PC)? Then I'd add it to the "green list" with that explanation, to also get rid of the warning:

```yaml
    usesCleartextTraffic: used for synchronization with the PC companion in the local network
```

The `DEPENDENCY_INFO_BLOCK` is easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by r57zone** [comment]
The application uses synchronization with the computer in local network, http connections are used. If it is used for synchronization with an external web server, then the user himself decides whether it will be http or https (by writing the protocol in the settings).

Does this apk have the DEPENDENCY_INFO_BLOCK problem?
[app-release.zip](https://github.com/r57zone/EasyNotes/files/14588766/app-release.zip)

**Comment by IzzySoft** [comment]
Nope, gone there.

**Comment by r57zone** [comment]
I'm planning an update, but I don't know when yet.

**Comment by IzzySoft** [comment]
I'd suggest deploying this change with that update then, if that's OK with you (if removing the blob was the only change done, and you want me to, I can replace the APK here so at least fresh installations get it). These blobs will start cause warnings here at one point probably, but certainly not before September or so. Too many other tasks to be completed before that :wink:

**Comment by r57zone** [comment]
yep, the only change is the removal of the blob.

**Comment by IzzySoft** [comment]
Now, that's funny. I can confirm the APKs are identical: I run `diff` over them, and `diff` showed **no difference** – still, one has the blob and the other does not. Very strange. Next I manually ran `rsync` to get it to the server, expecting `rsync` wouldn't do a thing as the files are "identical" – but `rsync` sync'd the file. Wow.

OK, but it is replaced now, so everything fine. Than you very much for your help!
